### ISSUE TITLE
go 1.6 panic

### ISSUE THREAD

**Issue by zygis** [mikkyang/id3-go#24]
```
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
panic(0x797660, 0xc8203e2070)
        /opt/go/src/runtime/panic.go:464 +0x3e6
github.com/djimenez/iconv-go.(*Converter).Convert(0xc820070f50, 0xc8203e2020, 0x4, 0x8, 0xc8203e2028, 0x8, 0x8, 0x0, 0x0, 0x0, ...)
        fakePath/dependencies/src/github.com/djimenez/iconv-go/converter.go:83 +0x2a4
github.com/djimenez/iconv-go.(*Converter).ConvertString(0xc820070f50, 0xc8203d6408, 0x4, 0x0, 0x0, 0x0, 0x0)
        fakePath/dependencies/src/github.com/djimenez/iconv-go/converter.go:123 +0x1f2
github.com/mikkyang/id3-go/encodedbytes.EncodedDiff(0x80d403, 0xc8203d6408, 0x4, 0x450400, 0xc8203d6408, 0x4, 0xc820000180, 0x0, 0x0)
        fakePath/dependencies/src/github.com/mikkyang/id3-go/encodedbytes/util.go:141 +0x69
github.com/mikkyang/id3-go/v2.(*TextFrame).SetEncoding(0xc820378000, 0x80d478, 0x5, 0x0, 0x0)
        fakePath/dependencies/src/github.com/mikkyang/id3-go/v2/frame.go:250 +0x170
github.com/mikkyang/id3-go/v2.(*Tag).setTextFrameText(0xc820288280, 0x80d220, 0x4, 0x85cb20, 0x1c, 0x8b5cf0, 0xc8203d6408, 0x4)
        fakePath/dependencies/src/github.com/mikkyang/id3-go/v2/id3v2.go:286 +0x510
github.com/mikkyang/id3-go/v2.(*Tag).SetArtist(0xc820288280, 0xc8203d6408, 0x4)
        fakePath/dependencies/src/github.com/mikkyang/id3-go/v2/id3v2.go:247 +0xd5
modules/downloader.DownloadAlbum(0x7fffeb3c45f3, 0x19, 0xc82006c380, 0x0, 0x0, 0x0, 0x0)
        fakePath/src/modules/someMyCode.go:68 +0x114c
main.main()

```

**Comment by mikkyang** [comment]
I think this is more of an issue with iconv-go?

**Comment by zygis** [comment]
Yes. Just checked, they already fixed issue.
