### ISSUE TITLE
Panic when reading tags concurrently

### ISSUE THREAD

**Issue by ceralena** [mikkyang/id3-go#31]
I'm writing a program that indexes a music library. I'm experimenting with making some operations concurrent to improve performance for very large libraries.

`id3-go` is panicking when I have several goroutines calling `id3.Open()` at the same time [1].

I'm happy to put in a pull request to fix this, but first I'd like to get your input on which approach to take.

I think the issue is coming from [reader.go#L69](https://github.com/mikkyang/id3-go/blob/master/encodedbytes/reader.go#L69), in `ReadRestString()`:

```go
return Decoders[encoding].ConvertString(string(b))
```

`Decoders` are defined at the package level as vars (see [here](https://github.com/mikkyang/id3-go/blob/master/encodedbytes/util.go#L31). I guess they have some kind of internal state, so they're not happy when multiple goroutines call `ConvertString()`.

I can think of two ways to fix this:

* have a set of mutexes - a mutex for each member of `Decoders` and `Encoders`
* just initialize decoders and encoders on-demand in the Reader & the Writer

I think the second one is cleaner and simpler, and involves less contention - but I don't have any context on the cost of creating them.

I've made the second change locally and id3-go is still blazing fast. 

Let me know. Keen to put in a PR if I get your feedback.

[1]
```
panic: runtime error: slice bounds out of range

goroutine 19 [running]:
github.com/djimenez/iconv-go.(*Converter).ConvertString(0xc4200705d0, 0xc4200369b8, 0x10, 0x10, 0xc4200369b8, 0x10, 0x0)
        /home/cera/src/vir/backend/vendor/src/github.com/djimenez/iconv-go/converter.go:155 +0x513
github.com/mikkyang/id3-go/encodedbytes.(*Reader).ReadRestString(0xc420036a90, 0x0, 0xc42000c980, 0x11, 0x11, 0x11)
        /home/cera/src/vir/backend/vendor/src/github.com/mikkyang/id3-go/encodedbytes/reader.go:69 +0x14f
github.com/mikkyang/id3-go/v2.ParseTextFrame(0x5d9829, 0x4, 0x5de24a, 0x1c, 0x5e2100, 0x1100000000, 0x0, 0xc42000c980, 0x11, 0x11, ...)
        /home/cera/src/vir/backend/vendor/src/github.com/mikkyang/id3-go/v2/frame.go:233 +0x266
github.com/mikkyang/id3-go/v2.ParseV23Frame(0x88ff00, 0xc42000e028, 0xc42000e028, 0x88ff00)
        /home/cera/src/vir/backend/vendor/src/github.com/mikkyang/id3-go/v2/id3v23.go:150 +0x43b
github.com/mikkyang/id3-go/v2.ParseTag(0x890880, 0xc42000e028, 0x2)
        /home/cera/src/vir/backend/vendor/src/github.com/mikkyang/id3-go/v2/id3v2.go:74 +0x19e
github.com/mikkyang/id3-go.Open(0xc4200b4700, 0x3f, 0x123dea0, 0x0, 0x0)
        /home/cera/src/vir/backend/vendor/src/github.com/mikkyang/id3-go/id3.go:58 +0x140
vir.loadTrackMetadataFromFile(0xc4200b4700, 0x3f, 0x0, 0x0, 0x0)
        /home/cera/src/vir/backend/src/vir/metadata.go:22 +0x82
vir.loadMetadataConcurrent.func1(0xc420070770, 0xc42006e120, 0xc42006e180)
        /home/cera/src/vir/backend/src/vir/index.go:192 +0x14e
created by vir.loadMetadataConcurrent
        /home/cera/src/vir/backend/src/vir/index.go:210 +0xfb
```

**Comment by ceralena** [comment]
Looks like this might be fixed by https://github.com/casept/id3-go/commit/2e21798b4999ccd0cd10fdb37e427712998d6fc2

**Comment by rosmo** [comment]
I can confirm that switching to @casept repository fixes string corruption issues for me when processing tags in concurrent goroutines.
